services:
  backend:
    build: ./backend
    container_name: atendimento_backend
    ports:
      - "8765:8765"
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_NAME=db_atendimentos
      - DB_USER=root
      - DB_PASSWORD=root
    entrypoint: /var/www/html/entrypoint.sh

  mysql:
    image: mysql:8.0
    container_name: atendimento_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_atendimentos
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 5s
      retries: 5

volumes:
  db_data:
  backend_vendor: